services:
  api:
    image: mahdidev3/kanonix-backend:latest
    ports:
      - "8000:8000"
  arya-frontend:
    build:
      context: .
      target: dev
    ports:
      - "5173:5173"
    env_file:
      - .env.development
    depends_on:
      - api
